-- =====================================================
-- BNCC Computacional – Educação Infantil (EI03CO01 a EI03CO11)
-- Adaptado do script Gemini para a tabela bncc_computacional.
-- Execute após: create-bncc-computacional.sql, add-codigo-habilidade-bncc.sql e add-materiais-complementares-bncc.sql
-- INSERT IGNORE: pode rodar de novo sem duplicar (mesmo id por código).
-- =====================================================

INSERT IGNORE INTO bncc_computacional (id, tipo_nivel, ano_etapa, codigo_habilidade, habilidade, eixo, objetivo_aprendizagem, explicacao_habilidade, exemplos, materiais_complementares, ordem) VALUES
('ei-ei03co01', 'educacao_infantil', 'Educação Infantil', 'EI03CO01', 'Reconhecer padrão de repetição em sequência de sons, movimentos, desenhos.', 'Pensamento Computacional', NULL, 'O reconhecimento de padrões é uma habilidade essencial para a programação de computadores, sendo aplicado em diversas áreas, como reconhecimento de imagens, processamento de sinais e análise de dados.', 'Plugada:\n1) Criar padrões de repetição em sequência com formas e cores diferentes: (i) editor de desenho; (ii) ferramenta online (Pattern Shapes). 2) Completar sequência de figuras em jogos online (Shape Pattern, Chicken Dance).\n\nDesplugada:\n1) Perceber a repetição de movimentos na rotina (comer, respirar). 2) Reconhecer padrão por meio de sons do corpo. 3) Criar sequência com blocos de montar.', 'Pattern Shapes, Shape Pattern, Chicken Dance', 1),
('ei-ei03co02', 'educacao_infantil', 'Educação Infantil', 'EI03CO02', 'Expressar as etapas para a realização de uma tarefa de forma clara e ordenada.', 'Pensamento Computacional', NULL, 'Expressar as etapas para a realização de uma tarefa de forma clara e ordenada é importante para que a tarefa seja executada corretamente e que possa ser entendida e executada por outras pessoas ou máquinas. Também ajuda a identificar possíveis erros e a simplificar o processo, tornando-o mais eficiente.', 'Plugada:\n1) Experienciar etapas de execução em jogos digitais: (i) Cookie Monsters Foodie Truck; (ii) Ready Set Grow).\n\nDesplugada:\n1) Expressar etapas de tarefas diárias (desenho ou oral). 2) Ordenar sequência de imagens (ex: Hora de dormir: banho, pijama, dentes, história, dormir).', NULL, 2),
('ei-ei03co03', 'educacao_infantil', 'Educação Infantil', 'EI03CO03', 'Experienciar a execução de algoritmos brincando com objetos (des)plugados.', 'Pensamento Computacional', NULL, 'A experiência de executar algoritmos brincando com objetos (des)plugados é importante porque permite que os estudantes sejam expostos a conceitos fundamentais de programação de uma forma mais concreta e fácil de compreender. Além disso, essa abordagem também pode ajudar a desenvolver habilidades importantes, como a resolução de problemas, a criatividade e a colaboração.', 'Plugada:\n1) Experienciar execução de algoritmos: (i) jogos digitais (Follow the Code); (ii) brinquedos robóticos.\n\nDesplugada:\n1) Percursos com desenhos no chão (labirinto, amarelinha). 2) Atividades manuais (dobraduras). Ex: Algoritmo para dobrar papel sulfite.', NULL, 3),
('ei-ei03co04', 'educacao_infantil', 'Educação Infantil', 'EI03CO04', 'Criar e representar algoritmos para resolver problemas.', 'Pensamento Computacional', NULL, 'A experiência de executar algoritmos brincando com objetos (des)plugados é importante porque permite que os estudantes sejam expostos a conceitos fundamentais de programação de uma forma mais concreta e fácil de compreender.', 'Plugada:\n1) Explorar jogos digitais e puzzles de sequência lógica (LightBot, Scratch Jr).\n\nDesplugada:\n1) Preparar uma receita evidenciando os passos (Minha Fábrica de Comida). 2) Criar percursos em tabuleiro representando passos (AlgoCards, Segue o Trilho).', 'AlgoCards', 4),
('ei-ei03co05', 'educacao_infantil', 'Educação Infantil', 'EI03CO05', 'Comparar soluções algorítmicas para resolver um mesmo problema.', 'Pensamento Computacional', NULL, 'Comparar soluções algorítmicas para resolver um mesmo problema é importante porque permite identificar a solução mais eficiente em termos de tempo de execução e utilização de recursos computacionais.', 'Plugada:\n1) Comparar diferentes rotas executadas em jogo digital de labirinto.\n\nDesplugada:\n1) Comparar rotas em labirinto no chão. 2) Comparar formas de realizar tarefas diárias (escovar dentes, tomar banho).', NULL, 5),
('ei-ei03co06', 'educacao_infantil', 'Educação Infantil', 'EI03CO06', 'Compreender decisões em dois estados (verdadeiro ou falso).', 'Pensamento Computacional', NULL, 'Compreender decisões em dois estados (verdadeiro ou falso) é importante porque é um dos princípios fundamentais da lógica booleana, que é a base para o funcionamento de muitos sistemas computacionais.', 'Plugada:\n1) Jogo digital de perguntas (Verdadeiro/Falso) usando Wordwall ou Jamboard.\n\nDesplugada:\n1) Perguntas com cartas verde (V) e vermelha (F). 2) Brincadeira morto/vivo adaptada para frases verdadeiras/falsas.', NULL, 6),
('ei-ei03co07', 'educacao_infantil', 'Educação Infantil', 'EI03CO07', 'Reconhecer dispositivos eletrônicos (e não-eletrônicos), identificando quando estão ligados ou desligados (abertos ou fechados).', 'Mundo Digital', NULL, 'Além de saber diferenciar o que são dispositivos eletrônicos e não eletrônicos, a habilidade trata da lógica booleana na identificação dos estados dos dispositivos, já que ela trabalha com valores "verdadeiro" ou "falso".', '(Des)plugada:\n1) Explorar dispositivos (lanterna, celular) para ligar/desligar. 2) Brincadeiras de dois estados: Seu Mestre Mandou, Estátua.', NULL, 7),
('ei-ei03co08', 'educacao_infantil', 'Educação Infantil', 'EI03CO08', 'Compreender o conceito de interfaces para comunicação com objetos (des)plugados.', 'Mundo Digital', NULL, 'A interface é o que permite que as pessoas interajam com os softwares de forma mais fácil e eficiente, possibilitando que realizem suas tarefas de maneira mais rápida e com menos erros.', 'Plugada:\n1) Reconhecer interfaces de aparelhos (micro-ondas, controle). 2) Representar interfaces no Paint.\n\nDesplugada:\n1) Brincar de telefone sem fio. 2) Desenhar interfaces (teclas de telefone).', NULL, 8),
('ei-ei03co09', 'educacao_infantil', 'Educação Infantil', 'EI03CO09', 'Identificar dispositivos computacionais e as diferentes formas de interação.', 'Mundo Digital', NULL, 'Identificar as diferentes formas de interação com os dispositivos permite que os alunos entendam como as pessoas interagem com as máquinas e, a partir disso, desenvolvam interfaces mais eficientes e acessíveis.', 'Plugada:\n1) Brincar com tablets/mesas interativas verificando formas de uso: toque, mouse, voz, gestos.\n\nDesplugada:\n1) Jogo de adivinhação sobre formas de interação. 2) Storyboards manuais sobre uso de dispositivos.', NULL, 9),
('ei-ei03co10', 'educacao_infantil', 'Educação Infantil', 'EI03CO10', 'Utilizar tecnologia digital de maneira segura, consciente e respeitosa.', 'Cultura Digital', NULL, 'Saber utilizar tecnologia digital de maneira segura, consciente e respeitosa é importante na educação infantil porque garante a integridade física e psicológica dos estudantes.', 'Plugada:\n1) Caça ao tesouro digital (Google Forms) sobre segurança. 2) Produzir portfólio digital (Book Creator).\n\nDesplugada:\n1) Caça ao tesouro com pistas sobre situações reais de ética. 2) Portfólio físico sobre segurança.', 'Escape Factory, Genial.ly, Book Creator, Flipgrid, Canva', 10),
('ei-ei03co11', 'educacao_infantil', 'Educação Infantil', 'EI03CO11', 'Adotar hábitos saudáveis de uso de artefatos computacionais, seguindo recomendações de órgãos de saúde competentes.', 'Cultura Digital', NULL, 'Adotar hábitos saudáveis de uso de artefatos computacionais é importante para prevenir problemas de saúde, como a Síndrome do Olho Seco e L.E.R., e evitar exposição excessiva a telas.', 'Plugada:\n1) Uso de óculos sem grau com tampões para simular dificuldade visual por tempo de tela. 2) Analisar jogos digitais e seus estímulos.\n\nDesplugada:\n1) Mesma estratégia dos óculos/tampões usando teatro de fantoches ao invés de tela.', NULL, 11);
