/* ==========================================================================
   INSERÇÃO DE DADOS: 6º AO 9º ANO (FUNDAMENTAL II)
   Adaptado do script Gemini para as tabelas curriculo_*.
   Execute após: curriculo-computacao-educacao-infantil.sql, curriculo-1ano-inserts.sql e curriculo-2ao5-ano-inserts.sql
   ========================================================================== */

-- 1. Inserir Etapas (6º, 7º, 8º, 9º Ano)
INSERT INTO curriculo_etapas_ensino (id, nome) VALUES
(7, '6º Ano'),
(8, '7º Ano'),
(9, '8º Ano'),
(10, '9º Ano')
ON DUPLICATE KEY UPDATE nome = VALUES(nome);

-- 2. Habilidades (6º Ano)
INSERT INTO curriculo_habilidades (id, etapa_id, codigo, eixo, descricao, explicacao) VALUES
(53, 7, 'EF06CO01', 'Pensamento Computacional', 'Classificar informações, agrupando-as em coleções (conjuntos) e associando cada coleção a um "tipo de dados"', 'As informações são armazenadas de diferentes maneiras, dependendo do tipo de dado que ela representa. Basicamente existem três tipos primitivos de dados: inteiros, real e string.'),
(54, 7, 'EF06CO02', 'Pensamento Computacional', 'Elaborar algoritmos que envolvam instruções sequenciais, de repetição e de seleção usando uma linguagem de programação.', 'Existem diferentes linguagens de programação que podem ser usadas para descrever algoritmos em diferentes níveis de abstração, como linguagens visuais, orientadas a objetos, funcionais, entre outras. Uma ou mais linguagens podem ser escolhidas para serem adotadas.'),
(55, 7, 'EF06CO03', 'Pensamento Computacional', 'Descrever com precisão a solução de um problema, construindo o programa que implementa a solução descrita.', 'É importante que se consiga expressar a solução do problema (algoritmo) em português, compreendendo que o programa é apenas uma descrição deste algoritmo em uma linguagem de programação. O aluno precisa entender que o mais importante é a construção do algoritmo. Notem que a ideia aqui não é apenas descrever as linhas de código em português, mas sim descrever em um alto nível de abstração como o problema é resolvido.'),
(56, 7, 'EF06CO04', 'Pensamento Computacional', 'Construir soluções de problemas usando a técnica de decomposição e automatizar tais soluções usando uma linguagem de programação.', 'Decomposição é uma das principais técnicas de resolução de problemas, onde um problema é dividido em subproblemas, os quais são resolvidos independentemente, e cujas soluções são combinadas para construir a solução do problema original. Algumas vantagens da decomposição são: permitir uma melhor organização e visualização do problema e da solução; facilitar o trabalho em grupo; permitir que possamos reutilizar as soluções dos subproblemas em outros problemas.'),
(57, 7, 'EF06CO05', 'Pensamento Computacional', 'Identificar os recursos ou insumos necessários (entradas) para a resolução de problemas, bem como os resultados esperados (saídas), determinando os respectivos tipos de dados, e estabelecendo a definição de problema como uma relação entre entrada e saída.', 'Definir problemas é uma habilidade muito importante, pois é o primeiro passo da solução. A definição de um problema se dá identificando quais são os tipos de entradas necessárias (insumos/informações) e qual o tipo da saída. Como a solução (algoritmo) deve ser genérica, se define um problema em termos dos tipos das entradas e saída. O objetivo aqui NÃO é propor soluções de problemas, e sim definir o que é necessário para resolvê-los e qual será o resultado esperado.'),
(58, 7, 'EF06CO06', 'Pensamento Computacional', 'Comparar diferentes casos particulares (instâncias) de um mesmo problema, identificando as semelhanças e diferenças entre eles, e criar um algoritmo para resolver todos, fazendo uso de variáveis (parâmetros) para permitir o tratamento de todos os casos de forma genérica.', 'Idealmente, um algoritmo é uma solução genérica: ele resolve várias instâncias de um problema. Por exemplo, um algoritmo que calcula a média aritmética de 2 números resolve este problema para qualquer par de números (que são as instâncias do problema). Para descrever um algoritmo de forma genérica, é necessário dar nomes às entradas do algoritmo. Esses nomes são chamados de variáveis ou parâmetros do algoritmo.'),
(59, 7, 'EF06CO07', 'Mundo Digital', 'Entender o processo de transmissão de dados, como a informação é quebrada em pedaços, transmitida em pacotes através de múltiplos equipamentos, e reconstruída no destino.', 'O processo de transmissão de dados envolve em dividir a informação em pedaços para que ela seja mais facilmente enviada através da rede de comunicação. Esses pedaços são transmitidos através de caminhos compostos por diferentes equipamentos. Finalmente, a informação é remontada no destino. Ao ser dividida, problemas que ocorram na transmissão em alguns pedaços da informação podem ser solucionados pelo reenvio de pedaços faltantes, corrompidos, ou fora de ordem.'),
(60, 7, 'EF06CO08', 'Mundo Digital', 'Compreender e utilizar diferentes formas de armazenar, manipular, compactar e recuperar arquivos, documentos e metadados.', 'O gerenciamento de dados é frequentemente realizado através do conceito de arquivo. Neste contexto, os arquivos são criados considerando alguma lógica interna e armazenados em memória secundária. Posteriormente, esses arquivos podem ser recarregados a fim de seus dados serem utilizados ou mesmo editados. Finalmente, os arquivos podem ser compactados para diminuir o espaço ocupado na memória secundária.'),
(61, 7, 'EF06CO09', 'Cultura Digital', 'Apresentar conduta e linguagem apropriadas ao se comunicar em ambiente digital, considerando a ética e o respeito.', 'Nesta habilidade é importante que os alunos possam vivenciar, discutir e refletir sobre o comportamento ao se comunicar em ambiente digital, principalmente na internet mas não limitada a ela(por exemplo também em aplicativos de conversa).'),
(62, 7, 'EF06CO10', 'Cultura Digital', 'Analisar o consumo de tecnologia na sociedade, compreendendo criticamente o caminho da produção dos recursos bem como aspectos ligados à obsolescência e a sustentabilidade.', 'Importante nesta habilidade considerar a reflexão sobre as perspectivas do ser humano e o consumo de tecnologia, como quando compramos novos celulares em substituição a aparelhos mais antigos, ou uma televisão, dentre outros, ou seja, nossos hábitos. Quantos recursos são necessários para se produzir uma tecnologia?')
ON DUPLICATE KEY UPDATE eixo = VALUES(eixo), descricao = VALUES(descricao), explicacao = VALUES(explicacao);

-- 3. Habilidades (7º Ano)
INSERT INTO curriculo_habilidades (id, etapa_id, codigo, eixo, descricao, explicacao) VALUES
(63, 8, 'EF07CO01', 'Pensamento Computacional', 'Criar soluções de problemas para os quais seja adequado o uso de registros e matrizes unidimensionais para descrever suas informações e automatizá-las usando uma linguagem de programação.', 'Para automatizar a solução de um problema através da construção de um programa de computador, normalmente é necessário definir as estruturas de dados que serão usadas. Uma das estruturas mais usadas é o registro, que permite descrever objetos identificando atributos destes objetos. Matrizes unidimensionais (ou vetores) podem ser usados quando temos situações nas quais queremos representar que um determinado objeto é composto por vários elementos similares.'),
(64, 8, 'EF07CO02', 'Pensamento Computacional', 'Analisar programas para detectar e remover erros, ampliando a confiança na sua correção.', 'Deve-se estimular a análise crítica do programa construído. Uma das formas é através da depuração, que consiste em uma análise detalhada do código e realização de testes para identificar erros. Depuração é uma das formas de desenvolver a habilidade do pensamento crítico.'),
(65, 8, 'EF07CO03', 'Pensamento Computacional', 'Construir soluções computacionais de problemas de diferentes áreas do conhecimento, de forma individual e colaborativa, selecionando as estruturas de dados e técnicas adequadas, aperfeiçoando e articulando saberes escolares.', 'Uma estrutura de dados em ciência da computação, é uma coleção tanto de valores (e seus relacionamentos) quanto de operações (sobre os valores e estruturas decorrentes). É uma implementação concreta de um tipo abstrato de dado ou um tipo de dado básico ou primitivo.'),
(66, 8, 'EF07CO04', 'Pensamento Computacional', 'Explorar propriedades básicas de grafos.', 'Grafos possuem muitas propriedades que podem ser úteis para a descoberta de conhecimento. Por exemplo, comunidades virtuais são caracterizadas por uma propriedade que se chama clique de um grafo. Algumas propriedades de grafos são: coloração, cliques, graus de vértices, diâmetro, pontes.'),
(67, 8, 'EF07CO05', 'Pensamento Computacional', 'Criar algoritmos fazendo uso da decomposição e do reúso no processo de solução de forma colaborativa e cooperativa e automatizá-los usando uma linguagem de programação.', 'A decomposição facilita o trabalho cooperativo, pois auxilia na identificação clara de cada subtarefa (subproblema), que pode ser realizada por diferentes equipes, bem como da forma como os resultados das tarefas devem ser combinados. A identificação precisa das interfaces das tarefas (entradas e saídas) é essencial para viabilizar a combinação das soluções dessas tarefas, bem como o reúso das mesmas.'),
(68, 8, 'EF07CO06', 'Mundo Digital', 'Compreender o papel de protocolos para a transmissão de dados.', 'A transmissão de dados precisa ser realizada considerando um conjunto de regras para sua execução correta. Esse conjunto de regras é chamado de protocolo e permite que a transmissão de dados seja realizada de forma consistente por diferentes equipamentos.'),
(69, 8, 'EF07CO07', 'Mundo Digital', 'Identificar problemas de segurança cibernética e experimentar formas de proteção.', 'A utilização de sistemas e redes de computadores precisa respeitar algumas propriedades fundamentos da segurança da informação, como confidencialidade, integridade e disponibilidade. No entanto, essas propriedades podem ser ameaçadas por eventos maliciosos ou não-maliciosos. A fim de diminuir a ocorrência desses eventos, mecanismos de proteção podem ser empregados.'),
(70, 8, 'EF07CO08', 'Cultura Digital', 'Demonstrar empatia sobre opiniões divergentes na web.', 'Nesta habilidade considera-se a discussão e reflexão de colocar-se em posição do outro e respeito em relação as opiniões divergentes na internet, como opiniões de estilos de música, de filmes, de roupas, dentre outros. Espera-se que o aluno possa ser capaz de reconhecer a importância de respeitar as opiniões diferentes da sua.'),
(71, 8, 'EF07CO09', 'Cultura Digital', 'Reconhecer e debater sobre cyberbullying.', 'O contexto desta habilidade é a de proporcionar ao aluno a reflexão e discussão sobre cyberbullying, trazendo sua definição. Além disso, espera-se que o aluno reflita sobre a importância de se combater o cyberbullying (essa prática de intimidação, humilhação, exposição, dentre outros em meio digital).'),
(72, 8, 'EF07CO10', 'Cultura Digital', 'Identificar os impactos ambientais do descarte de peças de computadores e eletrônicos, bem como sua relação com a sustentabilidade.', 'Esta habilidade sugere a reflexão e discussão sobre a relação da sustentabilidade e o impacto na produção e descarte de lixo eletrônico. Considera-se importante enfatizar o descarte de material tecnológico e as diferenças para outros tipos de lixo.'),
(73, 8, 'EF07CO11', 'Cultura Digital', 'Criar, documentar e publicar, de forma individual ou colaborativa, produtos (vídeos, podcasts, web sites) usando recursos de tecnologia.', 'Nesta habilidade espera-se que o aluno utilize recursos e ferramentas digitais como editores de vídeo, editor de áudio, de blogs, para produzir um vídeo, um áudio, uma página na internet, criando e publicando conteúdo, individualmente e colaborativamente.')
ON DUPLICATE KEY UPDATE eixo = VALUES(eixo), descricao = VALUES(descricao), explicacao = VALUES(explicacao);

-- 4. Habilidades (8º Ano)
INSERT INTO curriculo_habilidades (id, etapa_id, codigo, eixo, descricao, explicacao) VALUES
(74, 9, 'EF08CO01', 'Pensamento Computacional', 'Construir soluções de problemas usando a técnica de recursão e automatizar tais soluções usando uma linguagem de programação.', 'O conceito de recursão permite exercitar o pensamento indutivo na resolução de problemas, ou seja, recursão não deve ser entendida como uma questão sintática e sim como uma forma poderosa de resolver problemas. O raciocínio indutivo é muito útil na resolução de problemas, pois permite que se trabalhe em um nível de abstração mais elevado do que usando raciocínio dedutivo.'),
(75, 9, 'EF08CO02', 'Pensamento Computacional', 'Criar soluções de problemas para os quais seja adequado o uso de listas para descrever suas informações e automatizá-las usando uma linguagem de programação, empregando ou não a recursão como uma técnica de resolver o problema.', 'Fazer projetos e construir soluções usando listas e recursão. É importante salientar a importância da análise crítica de programas recursivos identificando a existência de um caso base (fim) e de chamadas recursivas que fazem o programa convergir (se aproximar do fim) - caso contrário os programas podem não terminar.'),
(76, 9, 'EF08CO03', 'Pensamento Computacional', 'Utilizar algoritmos clássicos de manipulação sobre listas.', 'Compreender algoritmos de manipulação de listas. Para isso, os alunos podem simular os algoritmos ou mesmo implementá-los.'),
(77, 9, 'EF08CO04', 'Pensamento Computacional', 'Construir soluções computacionais de problemas de diferentes áreas do conhecimento, de forma individual e colaborativa, selecionando as estruturas de dados e técnicas adequadas, aperfeiçoando e articulando saberes escolares.', 'Uma estrutura de dados em ciência da computação, é uma coleção tanto de valores (e seus relacionamentos) quanto de operações (sobre os valores e estruturas decorrentes).'),
(78, 9, 'EF08CO05', 'Mundo Digital', 'Compreender os conceitos de paralelismo, concorrência e armazenamento/processamento distribuídos.', 'O aluno deve compreender que o paralelismo permite a utilização de diferentes recursos para executar partes de uma tarefa que podem ser realizadas simultaneamente. Paralelismo ocorre quando mais de uma tarefa é executada ao mesmo tempo. Normalmente, se usa paralelismo para melhorar o tempo de execução de uma solução.'),
(79, 9, 'EF08CO06', 'Mundo Digital', 'Entender como é a estrutura e funcionamento da internet.', 'A internet é uma rede composta por muitas redes, as quais compartilham o protocolo Internet. Essas redes são agrupadas em sistemas autônomos, conjuntos de redes que possuem uma política de operação comum. A definição desses sistemas autônomos é realizada por entidades que operam na organização dos recursos da Internet.'),
(80, 9, 'EF08CO07', 'Cultura Digital', 'Compartilhar informações por meio de redes sociais, compreendendo a sua dinâmica de funcionamento, de forma responsável e avaliando sua confiabilidade, considerando o respeito e a ética.', 'A perspectiva desta habilidade é que o aluno tenha a vivência das redes sociais, identifique seu funcionamento como regras, cadastro, dentre outros aspectos operacionais. Além disso, espera-se que o aluno possa refletir sobre o uso responsável das redes sociais, discutindo ética e respeito ao interagir com o outro em meio digital.'),
(81, 9, 'EF08CO08', 'Cultura Digital', 'Distinguir os tipos de dados pessoais que são solicitados em espaços digitais e os riscos associados.', 'Nesta habilidade importante que o aluno identifique os tipos de dados pessoais (nome, endereço, documento de identidade) que são exigidos em diferentes espaços como jogos online, redes sociais, bem como refletir sobre os riscos de de compartilhar esses dados em espaços digitais como a internet.'),
(82, 9, 'EF08CO09', 'Cultura Digital', 'Analisar criticamente as políticas de termos de uso das redes sociais e demais plataformas.', 'Espera-se que o aluno possa discutir e analisar os termos e políticas de uso das redes sociais e demais plataformas, refletindo sobre suas implicações, como por exemplo em nossos dados pessoais que ficam armazenados.'),
(83, 9, 'EF08CO10', 'Cultura Digital', 'Discutir questões sobre segurança e privacidade relacionadas ao uso dos ambientes virtuais.', 'Destaca-se nessa habilidade a reflexão sobre aspectos de segurança e privacidade que são importantes quando utilizamos ambientes virtuais, como jogos online, compras online, interação em salas de conversa online, interação em redes sociais. Assim, destaca-se o compartilhamento de informações, acesso a sites da internet que não são seguros e desconhecidos, dentre outros.'),
(84, 9, 'EF08CO11', 'Cultura Digital', 'Avaliar a precisão, relevância, adequação, abrangência e vieses que ocorrem em fontes de informação eletrônica.', 'A perspectiva desta habilidade é que o aluno tenha a vivência e faça análise crítica de fontes de informações, como em jornais, blogs, canais de comunicação como YouTube, verificando suas características e como a informação é veiculada.')
ON DUPLICATE KEY UPDATE eixo = VALUES(eixo), descricao = VALUES(descricao), explicacao = VALUES(explicacao);

-- 5. Habilidades (9º Ano)
INSERT INTO curriculo_habilidades (id, etapa_id, codigo, eixo, descricao, explicacao) VALUES
(85, 10, 'EF09CO01', 'Pensamento Computacional', 'Criar soluções de problemas para os quais seja adequado o uso de árvores e grafos para descrever suas informações e automatizá-las usando uma linguagem de programação.', 'Grafos e árvores podem ser usados para representar uma gama enorme de informações. Para que possamos construir programas de computador, essas estruturas precisam ser formalizadas e descritas em linguagens de programação. Grafos são estruturas que permitem representar objetos e relacionamentos entre esses objetos (como redes sociais, mapas de cidades, a internet etc.). Uma árvore é um grafo com elementos organizados hierarquicamente.'),
(86, 10, 'EF09CO02', 'Pensamento Computacional', 'Construir soluções computacionais de problemas de diferentes áreas do conhecimento, de forma individual e colaborativa, selecionando as estruturas de dados e técnicas adequadas, aperfeiçoando e articulando saberes escolares.', 'Uma estrutura de dados em ciência da computação, é uma coleção tanto de valores (e seus relacionamentos) quanto de operações (sobre os valores e estruturas decorrentes). É uma implementação concreta de um tipo abstrato de dado ou um tipo de dado básico ou primitivo.'),
(87, 10, 'EF09CO03', 'Pensamento Computacional', 'Usar autômatos para descrever comportamentos de forma abstrata automatizando-os através de uma linguagem de programação baseada em eventos.', 'Linguagens baseadas em eventos permitem descrever sistemas que são orientados pela ocorrência de eventos (como cliques de mouse, pressionamento de alguma tecla, sinal de algum sensor). Para se desenvolver um programa orientado a eventos, é muito útil construir como primeiro passo uma especificação abstrata do sistema usando autômatos.'),
(88, 10, 'EF09CO04', 'Mundo Digital', 'Compreender o funcionamento de malwares e outros ataques cibernéticos.', 'Software malicioso, ou malware, são programas nocivos que obtêm acesso ilegal a dispositivos digitais. Eles podem acessar um computador ou dispositivo por meio de anexos de e-mail, pendrives ou sites desprotegidos. O malware pode invadir um computador e causar estragos. Esses programas podem desacelerar um dispositivo, enviar e-mails de spam ou até mesmo roubar ou excluir dados pessoais.'),
(89, 10, 'EF09CO05', 'Mundo Digital', 'Analisar técnicas de criptografia para armazenamento e transmissão de dados.', 'A criptografia é o processo de pegar uma mensagem e torná-la ilegível para todos, exceto para a pessoa a quem se destina. Historicamente, a razão mais popular para criptografar informações era permitir a comunicação entre líderes militares, espiões ou chefes de estado. Mais recentemente, com o advento da internet e das compras online, a criptografia está se tornando cada vez mais importante.'),
(90, 10, 'EF09CO06', 'Cultura Digital', 'Analisar problemas sociais de sua cidade e estado a partir de ambientes digitais, propondo soluções.', 'Espera-se que o aluno utilize recursos digitais para analisar problemas sociais de seu cotidiano, como por exemplo em pesquisa, comparação de informação, documentação da pesquisa, seja em sua cidade ou estado, propondo soluções a esses problemas.'),
(91, 10, 'EF09CO07', 'Cultura Digital', 'Avaliar aplicações e implicações políticas, socioambientais e culturais das tecnologias digitais para propor alternativas aos desafios do mundo contemporâneo, incluindo aqueles relativos ao mundo do trabalho.', 'Importante nessa habilidade que o aluno possa refletir, discutir as diversas aplicações das tecnologias em nosso cotidiano, considerando propor soluções aos desafios da atualidade do ser humano em qualquer área, como por exemplo no meio ambiente, na saúde, na economia, acessibilidade, transporte, dentre outros.'),
(92, 10, 'EF09CO08', 'Cultura Digital', 'Discutir como a distribuição desigual de recursos de computação em uma economia global levanta questões de equidade, acesso e poder.', 'Nesta habilidade espera-se que o aluno possa refletir sobre o acesso as tecnologias pelas pessoas e seus impactos na igualdade, desenvolvimento sustentável, e poder, como por exemplo sobre os custos de determinada tecnologia e quem pode comprá-la, trazendo assim questões como pobreza, acesso ao poder, dentre outros.'),
(93, 10, 'EF09CO09', 'Cultura Digital', 'Criar ou utilizar conteúdo em meio digital, compreendendo questões éticas relacionadas a direitos autorais e de uso de imagem.', 'Espera-se que o aluno possa utilizar recursos como editores de texto, planilha, apresentações, editores de vídeo, blogs, programas de animação, linguagens de programação, para criar conteúdos diversos considerando o cuidado com direitos autorais.'),
(94, 10, 'EF09CO10', 'Cultura Digital', 'Avaliar a veracidade, credibilidade e relevância da informação em seus diferentes formatos, sendo capaz de identificar o propósito pelo qual foi disseminada.', 'Nesta habilidade o aluno terá a perspectiva de refletir e discutir sobre o papel da informação que circula em diferentes formatos (físico ou digital), analisando se é verídico, se tem credibilidade, sua importância e relevância, bem como relacionando a intenção dessa informação e sua circulação.')
ON DUPLICATE KEY UPDATE eixo = VALUES(eixo), descricao = VALUES(descricao), explicacao = VALUES(explicacao);

-- 6. Exemplos Práticos (Anos 6 ao 9)
INSERT INTO curriculo_exemplos_praticos (habilidade_id, tipo, conteudo) VALUES
(53, 'Geral', 'Encontrar um Ás em um baralho (lista de cartas). Calcular a média das provas dos alunos (lista de provas).'),
(54, 'Geral', 'Calcular a média de notas de uma turma em uma dada disciplina e informar se o resultado está acima da média do colégio.'),
(55, 'Geral', 'Desenvolver um programa que: (1) Se o ponteiro do mouse tocar no animal então o animal andará 10 passos. (2) Dada uma pilha de cartas, verificar se há ás.'),
(56, 'Geral', 'Decompor o problema de desenhar imagens em subproblemas de desenhar formas básicas. Decompor o problema de desenhar uma casa em polígonos regulares.'),
(57, 'Geral', 'Para encontrar um Ás em um baralho, precisa-se de um baralho e o resultado é uma carta; para calcular média, precisa-se de lista de notas e resultado é número.'),
(58, 'Geral', 'Comparar instâncias do problema de calcular área de retângulo e criar algoritmo genérico usando variáveis base e altura.'),
(59, 'Geral', 'Utilizar alunos como equipamentos de transmissão passando frases em pedaços de papel. Simular falha na entrega.'),
(60, 'Geral', 'Utilizar arquivo físico para simular sistema de arquivos e manipular pastas.'),
(61, 'Geral', 'Identificar e refletir sobre conduta on-line, propondo regras para debate de questões éticas.'),
(62, 'Geral', 'Refletir sobre sustentabilidade e tecnologia, identificando formas de economizar energia e desligar dispositivos.'),
(63, 'Geral', 'Programa que lê dados de documento de identidade e calcula idade. Programa de cadastro de grupos de pessoas (nome, telefone, data nascimento).'),
(64, 'Geral', 'Usar aplicativos que permitem monitorar execução do programa, parar, reiniciar e ativar pontos de parada.'),
(65, 'Geral', 'Identificar estrutura de dados para programa de imagens (matriz de pixels) ou jogo no Scratch (lista de pontuação).'),
(66, 'Geral', 'Analisar estrutura de conexão em rede social ou solucionar problema de entregas em mapa de cidade.'),
(67, 'Geral', 'Algoritmo para organizar baralho por naipe e numeração: dividir em separar naipes, ordenar cartas de cada naipe e juntar montes.'),
(68, 'Geral', 'Definir regras de encaminhamento em brincadeira de telefone sem fio e instruir alunos a não cumprir regras para ver impacto.'),
(69, 'Geral', 'Demonstrar como segredos compartilhados espalham (histórias). Esquemas de criptografia com dicionário de códigos.'),
(70, 'Geral', 'Demonstrar respeito a diferentes opiniões em debate sobre escolhas musicais ou política.'),
(71, 'Geral', 'Debate a partir de estudo de caso real sobre cyberbullying e propor ações para solucionar.'),
(72, 'Geral', 'Estudo sobre impacto das toxinas químicas quando hardwares são descartados de forma indevida.'),
(73, 'Geral', 'Detalhar processo de documentação de projeto, organizando linha do tempo.'),
(74, 'Geral', 'Solução recursiva para definir tamanho de lista. Solução recursiva para encontrar número de ascendentes de olhos azuis em árvore genealógica.'),
(75, 'Geral', 'Fazer um programa que junte as duas pilhas de cartas ordenadas de forma que o baralho todo continue ordenado.'),
(76, 'Geral', 'Simular ou programar algoritmos de ordenação (Bubblesort, Mergesort) e busca (linear, binária).'),
(77, 'Geral', 'Identificar estrutura adequada: matriz para pixels de imagem, lista para pontuação em jogo.'),
(78, 'Geral', 'Analisar funcionalidades de sistema web que dependem de concorrência. Internet como sistema distribuído.'),
(79, 'Geral', 'Usar lógica de modelo em camadas e mostrar como língua comum traduz comunicações entre línguas sem tradutores diretos.'),
(80, 'Geral', 'Utilizar redes sociais para compartilhar informações, como evento ou acontecimento com colegas.'),
(81, 'Geral', 'Criar lista de sites elencando tipos de dados pessoais solicitados e avaliando riscos.'),
(82, 'Geral', 'Identificar elementos polêmicos de políticas de termos de uso e aspectos para melhor proteção.'),
(83, 'Geral', 'Verificar configurações-padrão de privacidade e tomar consciência de filtros utilizados.'),
(84, 'Geral', 'Realizar pesquisa na internet usando palavras-chave, identificar relação com respostas e analisar ranqueamento.'),
(85, 'Geral', 'Algoritmo para encontrar caminho em mapa (grafo). Algoritmo para encontrar filhos em árvore genealógica.'),
(86, 'Geral', 'Identificar estrutura de dados para manipular imagens (matriz) ou pontuação de jogos (lista).'),
(87, 'Geral', 'Modelar comportamento de robô utilizando autômatos, descrevendo eventos de sensores.'),
(88, 'Geral', 'Analisar tipos de malware a partir de exemplos históricos (Brain, Morris Worm).'),
(89, 'Geral', 'Usar algoritmos simples para codificar textos e trocar mensagens. Discutir papel da criptografia na Segunda Guerra.'),
(90, 'Geral', 'Apresentar propostas para problemas da cidade usando fórum ou recurso digital aberto.'),
(91, 'Geral', 'Analisar surgimento de novas profissões e extinção de outras devido à automatização.'),
(92, 'Geral', 'Organizar painel online comparando tecnologias, custos e impactos no cotidiano.'),
(93, 'Geral', 'Discutir sobre direito autoral de músicas e filmes e prática de pirataria.'),
(94, 'Geral', 'Trabalhar com fake news, diferenciando informações falsas e verdadeiras e propondo reflexão sobre responsabilidade.');
