/* ==========================================================================
   INSERÇÃO DE DADOS: ENSINO MÉDIO (BLOCO FINAL)
   Adaptado do script Gemini para as tabelas curriculo_*.
   Execute após: curriculo-computacao-educacao-infantil.sql, curriculo-1ano-inserts.sql,
   curriculo-2ao5-ano-inserts.sql e curriculo-6ao9-ano-inserts.sql
   ========================================================================== */

-- 1. Inserir Etapa (Ensino Médio – bloco único na BNCC Computação)
INSERT INTO curriculo_etapas_ensino (id, nome) VALUES (11, 'Ensino Médio')
ON DUPLICATE KEY UPDATE nome = VALUES(nome);

-- 2. Habilidades (IDs 95 a 120)
INSERT INTO curriculo_habilidades (id, etapa_id, codigo, eixo, descricao, explicacao) VALUES
(95, 11, 'EM13CO01', 'Pensamento Computacional', 'Explorar e construir a solução de problemas por meio da reutilização de partes de soluções existentes.', 'Considerando que esta habilidade já vem sendo trabalhada desde o Ensino Fundamental, nesta etapa serão trabalhados principalmente dois tópicos (i) pelo lado mais prático, deve ser enfatizado o reuso de códigos de bibliotecas, (ii) pelo lado conceitual, deve-se trabalhar a construção da solução através da comparação (transformando) do problema a ser resolvido com outros problemas já solucionados, e assim reusando (e eventualmente adaptando) as soluções existentes.'),
(96, 11, 'EM13CO02', 'Pensamento Computacional', 'Explorar e construir a solução de problemas por meio de refinamentos, utilizando diversos níveis de abstração desde a especificação até a implementação.', 'Aplicar boas práticas da Engenharia de Software, tanto para construir uma solução usando níveis de abstração diferentes partindo da definição dos requisitos, especificação, projeto e implementação (refinamento vertical), quanto para fazer a evolução do sistema partindo de um protótipo e inserindo gradualmente as funcionalidades desejadas até chegar ao sistema completo (refinamento horizontal).'),
(97, 11, 'EM13CO03', 'Pensamento Computacional', 'Identificar o comportamento dos algoritmos no que diz respeito ao consumo de recursos como tempo de execução, espaço de memória e energia, entre outros.', 'Conhecer os princípios da complexidade de algoritmos, identificando as principais classes de funções que descrevem o consumo de recursos (tempo, espaço, energia) por algoritmos. Essas classes são caracterizadas por funções estudadas na Matemática no Ensino Média (polinomiais, logarítmicas, exponenciais). É importante compreender, por exemplo, que um algoritmo que executa em tempo polinomial é mais eficiente que um que executa em tempo exponencial.'),
(98, 11, 'EM13CO04', 'Pensamento Computacional', 'Reconhecer o conceito de metaprogramação como uma forma de generalização na construção de programas, permitindo que algoritmos sejam entrada ou saída para outros algoritmos.', 'Pode-se construir programas que manipulam ou geram outros programas. Isto se chama metaprogramação. Com isto, se pode obter programas muito mais flexíveis, que podem ser utilizados em diversos contextos. Do ponto de vista teórico, o conceito é importante para analisarmos os limites do que pode ser resolvido com programas de computador (teoria da Computabilidade).'),
(99, 11, 'EM13CO05', 'Pensamento Computacional', 'Identificar os limites da Computação para diferenciar o que pode ou não ser automatizado, buscando uma compreensão mais ampla dos limites dos processos mentais envolvidos na resolução de problemas.', 'Existem problemas que não têm solução computacional, o exemplo clássico é o Problema da Parada. A existência de uma solução para este problema levaria a um paradoxo. Isso mostra que os computadores não são (e nunca serão) capazes de resolver qualquer tipo de problema.'),
(100, 11, 'EM13CO06', 'Pensamento Computacional', 'Avaliar software levando em consideração diferentes características e métricas associadas.', 'A ideia desta habilidade é fazer com que os estudantes possam realizar avaliação de software, através da adoção de características (eficiência, usabilidade, portabilidade, correção, segurança, privacidade, referenciais éticas, entre outras) e métricas associadas, embasando cientificamente as suas escolhas.'),
(101, 11, 'EM13CO07', 'Mundo Digital', 'Compreender as diferentes tecnologias, bem como equipamentos, protocolos e serviços envolvidos no funcionamento de redes de computadores, identificando suas possibilidades de escala e confiabilidade.', 'Redes de Computadores como a Internet funcionam a partir de um conjunto de equipamentos (ex: bases Wi-Fi, switches, roteadores, firewalls) que realizam operações específicas e complementares. A comunicação entre os equipamentos acontece através de protocolos. Esta diversidade de equipamentos, protocolos e serviços cria um ambiente sofisticado que precisa ser administrado.'),
(102, 11, 'EM13CO08', 'Cultura Digital', 'Entender como mudanças na tecnologia afetam a segurança, incluindo novas maneiras de preservar sua privacidade e dados pessoais on-line, reportando suspeitas e buscando ajuda em situações de risco.', 'Esta habilidade visa a preparar os estudantes para fazer análise crítica sobre as tecnologias a que têm acesso, sendo capaz de identificar, a cada atualização, os riscos a que estão expostos e saber como se proteger e denunciar situações suspeitas.'),
(103, 11, 'EM13CO09', 'Cultura Digital', 'Identificar tecnologias digitais, sua presença e formas de uso, nas diferentes atividades no mundo do trabalho.', 'Esta habilidade visa a conduzir os estudantes à percepção de quais são as ferramentas disponíveis no universo laboral e como cada uma delas pode ser utilizada para resolver determinado problema (ferramentas de produtividade, planilhas, software 3D, etc.).'),
(104, 11, 'EM13CO10', 'Mundo Digital', 'Conhecer os fundamentos da Inteligência Artificial, comparando-a com a inteligência humana, analisando suas potencialidades, riscos e limites.', 'A Inteligência Artificial (IA) refere-se a sistemas ou máquinas que imitam a inteligência humana para executar tarefas e tomar decisões. A grande contribuição da IA é a automatização de diversas tarefas cognitivas. Porém, o uso indiscriminado e irresponsável dessas tecnologias pode ter consequências graves.'),
(105, 11, 'EM13CO11', 'Pensamento Computacional', 'Criar e explorar modelos computacionais simples para simular e fazer previsões, identificando sua importância no desenvolvimento científico.', 'Usar diferentes ferramentas de modelagem e simulação computacional para analisar sistemas simples e fazer previsões. Este tipo de modelagem envolve conceitos de probabilidade e estatística.'),
(106, 11, 'EM13CO12', 'Mundo Digital', 'Produzir, analisar, gerir e compartilhar informações a partir de dados, utilizando princípios de ciência de dados.', 'Ciência de dados é uma área visa a extração de conhecimento a partir de dados. Isso pode ser feito por diferentes processos apoiados por ferramentas computacionais, por exemplo planilhas, bancos de dados, ferramentas estatísticas e aprendizado de máquina.'),
(107, 11, 'EM13CO13', 'Mundo Digital', 'Analisar e utilizar as diferentes formas de representação e consulta a dados em formato digital para pesquisas científicas.', 'Esta habilidade visa a preparar os estudantes para fazer pesquisas eficazes, em bases de dados digitais, sendo capaz de criar e utilizar palavras-chave, fazer uso de filtros em buscadores avançados e identificar a origem da informação.'),
(108, 11, 'EM13CO14', 'Cultura Digital', 'Avaliar a confiabilidade das informações encontradas em meio digital, investigando seus modos de construção e considerando a autoria, a estrutura e o propósito da mensagem.', 'Visa preparar os estudantes para analisar as informações encontradas em meio digital sendo capaz de identificar a confiabilidade da informação, o quanto ela é atual, por quem ela foi produzida e a originalidade do texto.'),
(109, 11, 'EM13CO15', 'Mundo Digital', 'Analisar a interação entre usuários e artefatos computacionais, abordando aspectos da experiência do usuário e promovendo reflexão sobre a qualidade do uso dos artefatos nas esferas do trabalho, do lazer e do estudo.', 'Visa preparar os estudantes para analisar a interação entre usuários e artefatos computacionais, verificando a experiência do usuário no que tange as condições de acessibilidade, usabilidade e adequação ao público-alvo.'),
(110, 11, 'EM13CO16', 'Mundo Digital', 'Desenvolver projetos com robótica, utilizando artefatos físicos ou simuladores.', 'É possível desenvolver essa habilidade tanto usando kits físicos de robótica, quanto simuladores instalados em dispositivos computacionais ou online.'),
(111, 11, 'EM13CO17', 'Cultura Digital', 'Construir redes virtuais de interação e colaboração, favorecendo o desenvolvimento de projetos de forma segura, legal e ética.', 'Visa a fazer com que os estudantes sejam capazes de mobilizarem-se por meio de redes sociais, criando comunidades que possam articular propostas e projetos sociais ou científicos (ex: crowdfunding).'),
(112, 11, 'EM13CO18', 'Cultura Digital', 'Planejar e gerenciar projetos integrados às áreas de conhecimento de forma colaborativa, solucionando problemas, usando diversos artefatos computacionais.', 'Visa preparar os estudantes para utilizar artefatos computacionais para planejar e gerenciar projetos sendo capaz de integrar recursos para gestão de cronogramas, riscos e equipes.'),
(113, 11, 'EM13CO19', 'Cultura Digital', 'Expor, argumentar e negociar propostas, produtos e serviços, utilizando diferentes mídias e ferramentas digitais.', 'Visa preparar os estudantes para vender uma ideia fazendo uso de diferentes recursos tecnológicos, além de entender o comportamento das ferramentas de marketing digital.'),
(114, 11, 'EM13CO20', 'Cultura Digital', 'Criar conteúdos, disponibilizando-os em ambientes virtuais para publicação e compartilhamento, avaliando a confiabilidade e as consequências da disseminação dessas informações.', 'Visa preparar os estudantes para criarem conteúdos de diversas naturezas (podcasts, vídeos, textos) para serem disseminados em ambientes virtuais, refletindo sobre seus alcances.'),
(115, 11, 'EM13CO21', 'Cultura Digital', 'Comunicar ideias complexas de forma clara por meio de objetos digitais como mapas conceituais, infográficos, hipertextos e outros.', 'Visa preparar os estudantes para utilizar recursos digitais que os ajudem a fazer sínteses e correlações entre ideias, traduzindo informações complexas em ideias mais simples.'),
(116, 11, 'EM13CO22', 'Cultura Digital', 'Produzir e publicar conteúdo como textos, imagens, áudios, vídeos e suas associações, bem como ferramentas para sua integração, organização e apresentação, utilizando diferentes mídias digitais.', 'Visa preparar os estudantes para escolher e utilizar a ferramenta digital mais adequada de acordo com o propósito da mensagem e público-alvo.'),
(117, 11, 'EM13CO23', 'Cultura Digital', 'Analisar criticamente as experiências em comunidades virtuais e as relações advindas da interação e comunicação com outras pessoas, bem como seus impactos na sociedade.', 'Criar oportunidades de reflexão sobre as oportunidades de diálogo e alcance da mensagem que se configuram na formação de comunidades virtuais.'),
(118, 11, 'EM13CO24', 'Cultura Digital', 'Identificar e reconhecer como as redes sociais e artefatos computacionais em geral interferem na saúde física e mental de seus usuários.', 'Sensibilizar os estudantes sobre o impacto do uso excessivo das tecnologias para sua saúde (depressão, fobia, baixa autoestima, LER, etc.).'),
(119, 11, 'EM13CO25', 'Cultura Digital', 'Dialogar em ambientes virtuais com segurança e respeito às diferenças culturais e pessoais, reconhecendo e denunciando atitudes abusivas.', 'Preparar os estudantes para interagir e se comunicar em ambientes virtuais com respeito aos sujeitos envolvidos, buscando entender o contexto destas pessoas.'),
(120, 11, 'EM13CO26', 'Cultura Digital', 'Aplicar os conceitos e pressupostos do direito digital em sua conduta e experiências com o cotidiano da cultura digital, bem como na produção e uso de artefatos computacionais.', 'Orientar sobre respeito a Lei Geral de Proteção de Dados (LGPD), Marco Civil, direitos autorais e licenças na produção e uso de artefatos.')
ON DUPLICATE KEY UPDATE eixo = VALUES(eixo), descricao = VALUES(descricao), explicacao = VALUES(explicacao);

-- 3. Exemplos Práticos (Ensino Médio)
INSERT INTO curriculo_exemplos_praticos (habilidade_id, tipo, conteudo) VALUES
(95, 'Geral', 'Utilização de bibliotecas de código com linguagens de programação textuais, uso de GitHub para elaborar soluções colaborativamente.'),
(96, 'Geral', 'Representar problemas delimitados em conjunto com outras áreas, como na Biologia, e partir de esboço geral para níveis crescentes de detalhamento.'),
(97, 'Geral', 'Testes de programas corretos que geram tempo inviável de execução. Exemplificar programas com tempo exponencial vs linear. Criptografia usando fatoração de números grandes.'),
(98, 'Geral', 'Construção de scripts em sistema operacional capazes de gerar outros scripts. Programa que aplica outro programa em vários arquivos de uma pasta.'),
(99, 'Geral', 'Mostrar paradoxos como o Paradoxo do Mentiroso e relacionar com o Problema da Parada. Discutir limites da inteligência humana vs computação.'),
(100, 'Geral', 'Definir critérios de qualidade (usabilidade, segurança) e avaliar sistemas desenvolvidos por colegas. Discussão crítica comparando avaliações.'),
(101, 'Geral', 'Estudo de topologias de rede. Uso de analisadores de pacotes. Habilitar/desabilitar serviços para ver impacto. Emular ataque e uso de firewall.'),
(102, 'Geral', 'Estudo de casos de perfis falsos de conhecidos para coleta de informações pessoais.'),
(103, 'Geral', 'Identificar quais ferramentas (trator, impressora 3D, mapa mental) resolveriam problemas específicos no trabalho.'),
(104, 'Geral', 'Analisar criticamente algoritmos de recomendação de streaming. Construir e avaliar pequenos sistemas de recomendação.'),
(105, 'Geral', 'Construir modelos de simulação para avaliar consumo de energia, envelhecimento da população, valorização de criptomoedas.'),
(106, 'Geral', 'Análise e previsão de comportamento de compra de clientes a partir de perfis de compras passadas.'),
(107, 'Geral', 'Estudo de metadados em documentos digitais e gerenciadores de referências bibliográficas.'),
(108, 'Geral', 'Avaliação sobre a origem da postagem de "fake news" por meio de busca dos locais originais de publicação.'),
(109, 'Geral', 'Estudo de interfaces em aplicativos de smartphones usados por pessoas da melhor idade.'),
(110, 'Geral', 'Projetos de trabalho com plataforma Arduino ou MakeCode.'),
(111, 'Geral', 'Exemplos de iniciativas como Sleeping Giants, crowdfunding para projetos comunitários.'),
(112, 'Geral', 'Utilizar ferramentas de produtividade para gerenciar projetos, organizar drives virtuais, fluxogramas, reuniões virtuais.'),
(113, 'Geral', 'Organizar grupos para criar produtos e defendê-los em banca. Pesquisas de aceitação (formulários), criar perfis em redes sociais para divulgar.'),
(114, 'Geral', 'Criação e postagens de vídeos no TikTok sobre conteúdos de Química.'),
(115, 'Geral', 'Comunicação de temática com infográfico por meio da ferramenta Canva.'),
(116, 'Geral', 'Construção de conteúdo multimídia de História com a ferramenta ActivePresenter.'),
(117, 'Geral', 'Uso de emojis para representação de emoções em comunidades virtuais baseadas em texto (WhatsApp).'),
(118, 'Geral', 'Estudo de tempos de uso em aparelhos eletrônicos de tela por parte de crianças.'),
(119, 'Geral', 'Diálogo estabelecido entre equipes durante uma partida em game multiplayer.'),
(120, 'Geral', 'Licenças de uso de imagens digitais; Marco Civil da Internet, LGPD, Creative Commons.');
